export const enInteractionTranslations: Record<string, string> = {
  'interaction.askOwner': 'Ask Owner',
  'interaction.askSecretary': 'Ask Secretary',
  'interaction.channelInternal': 'Internal Route',
  'interaction.channelTelegram': 'Telegram Route',
  'interaction.module.compliance': 'Compliance Monitor',
  'interaction.module.dailyBrief': 'Daily Operating Brief',
  'interaction.module.designAudit': 'Design Audit',
  'interaction.module.fundingDigest': 'Funding Digest',
  'interaction.module.governance': 'Governance Lab',
  'interaction.module.hiringSim': 'Hiring Simulation',
  'interaction.module.infrastructure': 'Infrastructure Layers',
  'interaction.module.notifications': 'Notification Centre',
  'interaction.module.onboarding': 'Onboarding',
  'interaction.module.profile': 'Virtual Employee Profile',
  'interaction.module.queueMonitor': 'Queue Monitor',
  'interaction.module.settings': 'Settings',
  'interaction.module.suites': 'Executive Suites',
  'interaction.module.triage': 'Triage Module',
  'interaction.module.vault': 'Vault Module',
  'interaction.module.vaultKnowledge': 'Vault Knowledge Repository',
  'interaction.module.weeklyReview': 'Friday Weekly Review',
  'interaction.module.workspace': 'Workspace',
  'interaction.owner': 'Owner',
  'interaction.placeholder': 'Request, feedback, or escalation. Use @name context as needed...',
  'interaction.secretary': 'Secretary',
  'interaction.send': 'Send',
  'interaction.sendFailed': 'Failed to send request. Please try again.',
  'interaction.sending': 'Sending...',
  'interaction.stateBlocked': 'blocked',
  'interaction.stateQueued': 'queued',
  'interaction.title': 'Director Feedback Backbone',
  'interaction.to': 'To'
}
