export const enOperationsTranslations: Record<string, string> = {
  'compliance.activeViolations': 'ACTIVE VIOLATIONS',
  'compliance.adherenceScore': 'ADHERENCE SCORE',
  'compliance.auditProtocol': 'Audit Assertion Protocol',
  'compliance.runAudit': 'Run Audit',
  'compliance.scanning': 'Scanning...',
  'compliance.subtitle': 'System-wide adherence and violation metrics.',
  'compliance.systemStatus': 'SYSTEM STATUS',
  'compliance.title': 'Compliance Monitor',
  'dailyBrief.approvalQueue': 'Director Approval Queue',
  'dailyBrief.approveYes': 'YES',
  'dailyBrief.compiling': 'Compiling...',
  'dailyBrief.defer': 'DEFER',
  'dailyBrief.enabledJobs': 'Enabled Jobs',
  'dailyBrief.expiresIn': 'Expires in',
  'dailyBrief.functionStatus': 'Function Status Summary',
  'dailyBrief.lastRun': 'Last run',
  'dailyBrief.nextRun': 'Next run',
  'dailyBrief.refreshBrief': 'Refresh Brief',
  'dailyBrief.rejectNo': 'NO',
  'dailyBrief.schedulerStatus': 'Scheduler Status',
  'dailyBrief.subtitle': 'Top requests, system status, and pending approvals.',
  'dailyBrief.title': 'Daily Operating Brief',
  'dailyBrief.topRequests': 'Top 3 Executive Requests',
  'dashboard.quickEdit.agentSuggestion': 'Agent suggestion',
  'dashboard.quickEdit.applySuggestion': 'Apply Suggested Goal Improvement',
  'dashboard.quickEdit.commitSuccess': 'Lifecycle refinement committed.',
  'dashboard.quickEdit.explicitCommit': 'Explicit Commit',
  'dashboard.quickEdit.kpiSaveFailed': 'Unable to save KPI update.',
  'dashboard.quickEdit.kpiSignal': 'KPI signal is',
  'dashboard.quickEdit.profileSaveFailed': 'Unable to save profile update.',
  'dashboard.quickEdit.proposedKpiTarget': 'Proposed KPI Target',
  'dashboard.quickEdit.refine': 'Refine Goal / KPI Target',
  'dashboard.quickEdit.selectProfileRequired': 'Select an agent profile before committing.',
  'dashboard.quickEdit.suggestionPrefix': 'Based on KPI signal',
  'dashboard.quickEdit.suggestionSuffix':
    'refine execution focus toward removing the current bottleneck and define one measurable weekly checkpoint.',
  'dashboard.quickEdit.title': 'Contextual Lifecycle Quick-Edit',
  'dashboard.quickEdit.triggeredBy': 'Triggered by',
  'dashboard.refresh': 'Refresh',
  'dashboard.refreshing': 'Refreshing...',
  'dashboard.subtitle': 'Consolidated runtime health and director highlights.',
  'dashboard.title': 'Operations Dashboard',
  'designAudit.lastScan': 'LAST SCAN',
  'designAudit.no': 'NO',
  'designAudit.overallHealth': 'OVERALL HEALTH',
  'designAudit.rulesetAdherence': 'Ruleset Adherence',
  'designAudit.runAudit': 'Run Audit',
  'designAudit.scanning': 'Scanning...',
  'designAudit.subtitle': 'Enforcing visual integrity and token adherence.',
  'designAudit.threshold': 'THRESHOLD',
  'designAudit.title': 'Design System Audit',
  'designAudit.tokensSynced': 'TOKENS SYNCED',
  'designAudit.value': 'Value',
  'designAudit.yes': 'YES',
  'executiveSuites.escalationRequired': 'Escalation Required',
  'executiveSuites.escalations': 'Escalations',
  'executiveSuites.feedbackResponses': 'Feedback Responses',
  'executiveSuites.generatedAt': 'Generated At',
  'executiveSuites.integrationSnapshot': 'Administration Integration Snapshot',
  'executiveSuites.lastTrendSync': 'Last Trend Sync',
  'executiveSuites.mode': 'Mode',
  'executiveSuites.noTrendOutput': 'Run intelligence to generate policy-impact recommendations.',
  'executiveSuites.policyArea': 'Recommended Policy Area',
  'executiveSuites.policySignals': 'Policy Signals',
  'executiveSuites.refresh': 'Refresh Snapshot',
  'executiveSuites.runningTrendIntelligence': 'Running Intelligence...',
  'executiveSuites.runTrendIntelligence': 'Run Social Trend Intelligence',
  'executiveSuites.socialTrendOutput': 'Social Trend Policy Impact Output',
  'executiveSuites.staffRows': 'Staff Rows',
  'executiveSuites.subtitle':
    'Run social trend intelligence and review policy-impact recommendations before governance escalation.',
  'executiveSuites.title': 'Director Office Intelligence',
  'executiveSuites.trendCount': 'Trend Count',
  'fundingDigest.activeInvestorPipeline': 'Active Investor Pipeline',
  'fundingDigest.cashInBank': 'CASH IN BANK',
  'fundingDigest.confidence': 'Confidence',
  'fundingDigest.monthlyBurn': 'MONTHLY BURN',
  'fundingDigest.months': 'months',
  'fundingDigest.performanceMetrics': 'Performance Metrics',
  'fundingDigest.runway': 'RUNWAY',
  'fundingDigest.subtitle': 'Runway, burn rate, and active investor CRM pipeline.',
  'fundingDigest.syncFinancials': 'Sync Financials',
  'fundingDigest.syncing': 'Syncing...',
  'fundingDigest.title': 'Funding Digest',
  'governance.action': 'ACTION',
  'governance.actor': 'ACTOR',
  'governance.approve': 'Approve',
  'governance.commit': 'Commit',
  'governance.decisionQueue': 'Decision Queue',
  'governance.defer': 'Defer',
  'governance.export': 'Export CSV',
  'governance.id': 'ID',
  'governance.lockdown': 'Lockdown',
  'governance.refresh': 'Refresh',
  'governance.reject': 'Reject',
  'governance.result': 'RESULT',
  'governance.timestamp': 'TIMESTAMP',
  'hiringSim.activeCandidates': 'ACTIVE CANDIDATES',
  'hiringSim.activePipeline': 'Active Pipeline',
  'hiringSim.matchScore': 'MATCH SCORE',
  'hiringSim.openRoles': 'OPEN ROLES',
  'hiringSim.processing': 'Processing...',
  'hiringSim.runScreen': 'Run Screen',
  'hiringSim.subtitle': 'Virtual candidate screening and role matching matrix.',
  'hiringSim.timeToFill': 'TIME TO FILL (AVG)',
  'hiringSim.title': 'Hiring Simulation',
  'infrastructure.activeAgents': 'ACTIVE AGENTS',
  'infrastructure.crisisProtocolActive': 'CRISIS PROTOCOL ACTIVE',
  'infrastructure.nominal': 'NOMINAL',
  'infrastructure.performanceTelemetry': 'Performance Telemetry (IPC Bridge)',
  'infrastructure.pinging': 'Pinging...',
  'infrastructure.pingIpcBridge': 'Ping IPC Bridge',
  'infrastructure.stabilityMode': 'STABILITY MODE',
  'infrastructure.subtitle': 'Local-first systems architecture and core performance metrics.',
  'infrastructure.target': 'Target',
  'infrastructure.title': 'Infrastructure Layers',
  'lifecycle.backstory': 'Backstory',
  'lifecycle.goal': 'Goal',
  'lifecycle.kpisCsv': 'KPIs (comma separated IDs)',
  'lifecycle.kpiStatus': 'Live KPI Status',
  'lifecycle.loading': 'Loading lifecycle snapshot...',
  'lifecycle.openSkillRegistry': 'Open Skill Registry',
  'lifecycle.saveFailed': 'Unable to save lifecycle data.',
  'lifecycle.saveSuccess': 'Lifecycle data saved successfully.',
  'lifecycle.skillMarkdown': 'Global Skill Markdown',
  'lifecycle.skillsCsv': 'Skills (comma separated IDs)',
  'lifecycle.unsavedChanges': 'Unsaved changes',
  'lifecycle.wizard.modeHelp':
    'Wizard mode: configure each virtual employee profile using the shared lifecycle renderer.',
  'notifications.activeAlerts': 'Active Alerts',
  'notifications.fetching': 'Fetching...',
  'notifications.markAllRead': 'Mark All Read',
  'notifications.refreshLogs': 'Refresh Logs',
  'notifications.subtitle': 'Centralized alert registry and severity feed.',
  'notifications.title': 'Notification Centre',
  'notifications.unread': 'UNREAD',
  'profile.agentHandshakes': 'Agent Handshakes',
  'profile.backstory': 'Backstory',
  'profile.canRequestFrom': 'Can Request From',
  'profile.crisisProtocol': 'CRISIS PROTOCOL',
  'profile.inactiveDuringStability': 'Inactive during Stability Mode',
  'profile.notFound': 'Profile not found.',
  'profile.performanceKpis': 'Performance KPIs',
  'profile.receivesFrom': 'Receives From',
  'profile.saveSkill': 'Save',
  'profile.toolInventory': 'Tool Inventory',
  'profile.workflow': '4-Stage Workflow',
  'providerSettings.apiEndpoint': 'API Endpoint',
  'providerSettings.apiKeyEncrypted': 'API Key (encrypted)',
  'providerSettings.apiKeyHelper': 'Your API key will be encrypted with master password',
  'providerSettings.avgLatency': 'Avg Latency',
  'providerSettings.calls': 'Calls',
  'providerSettings.configureProvider': 'Configure Provider',
  'providerSettings.contextWindow': 'Context Window (tokens)',
  'providerSettings.contextWindowHelper':
    'Maximum tokens for this model. Leave blank to use registry default.',
  'providerSettings.contextWindowPlaceholder': 'e.g., 32000',
  'providerSettings.disabled': 'Disabled',
  'providerSettings.enabled': 'Enabled',
  'providerSettings.endpoint': 'Endpoint',
  'providerSettings.errors': 'Errors',
  'providerSettings.examples.geminiModel': 'e.g., gemini-pro',
  'providerSettings.examples.lmStudioModel': 'e.g., local-model, mistral, neural-chat',
  'providerSettings.examples.openRouterEndpoint': 'e.g., https://openrouter.ai/api/v1',
  'providerSettings.examples.openRouterModel': 'e.g., openai/gpt-3.5-turbo, anthropic/claude-2',
  'providerSettings.executionProviders': 'Execution Providers',
  'providerSettings.geminiCli.description': 'Execute Gemini models via command-line interface',
  'providerSettings.geminiCli.installedNotice':
    'Gemini CLI must be installed locally. Configuration will be stored securely.',
  'providerSettings.geminiCli.note':
    'Requires Gemini CLI installed locally. Configuration stored encrypted.',
  'providerSettings.geminiCli.shortLabel': 'Gemini CLI',
  'providerSettings.geminiCli.title': 'Gemini CLI (Local/Terminal)',
  'providerSettings.lmStudio.description': 'Run LLMs locally on your machine via LM Studio API',
  'providerSettings.lmStudio.note': 'Download LM Studio from lmstudio.ai and start the server',
  'providerSettings.lmStudio.shortLabel': 'LM Studio',
  'providerSettings.lmStudio.title': 'LM Studio (Local)',
  'providerSettings.masterPassword.dialogDescription':
    'Enter a master password (minimum 16 characters) to encrypt your provider API keys and configurations.',
  'providerSettings.masterPassword.dialogTitle': 'Set Master Password',
  'providerSettings.masterPassword.label': 'Master Password',
  'providerSettings.masterPassword.minLength': 'Minimum 16 characters',
  'providerSettings.masterPassword.sectionDescription':
    'Set a master password to encrypt your provider API keys and sensitive configurations. Minimum 16 characters.',
  'providerSettings.masterPassword.sectionTitle': 'Master Password',
  'providerSettings.masterPassword.setButton': 'Set Master Password',
  'providerSettings.masterPassword.setPassword': 'Set Password',
  'providerSettings.model': 'Model',
  'providerSettings.openRouter.description':
    'Use OpenRouter to access multiple LLM providers including Claude, GPT, Llama',
  'providerSettings.openRouter.note':
    'Get your API key from openrouter.ai - NOT stored in Vault, kept locally encrypted',
  'providerSettings.openRouter.shortLabel': 'OpenRouter',
  'providerSettings.openRouter.title': 'OpenRouter (API)',
  'providerSettings.port': 'Port',
  'providerSettings.privacySecurityBody':
    'Model provider configurations (API keys, endpoints) are encrypted using AES-256-GCM and stored in LocalStorage only. They are never transmitted to the Vault or any external service without explicit action.',
  'providerSettings.privacySecurityTitle': 'Privacy & Security:',
  'providerSettings.reservedOutputTokens': 'Reserved Output Tokens',
  'providerSettings.reservedOutputTokensHelper':
    'Tokens reserved for model output. Leave blank to use registry default.',
  'providerSettings.reservedOutputTokensPlaceholder': 'e.g., 2048',
  'providerSettings.saveConfiguration': 'Save Configuration',
  'providerSettings.status': 'Status',
  'providerSettings.subtitle':
    'Configure local execution providers for Virtual Employees. API keys and sensitive configurations are encrypted and stored locally, NOT in the Vault. A master password protects your configuration.',
  'providerSettings.title': 'Provider Settings - Agent Model Execution',
  'providerSettings.usageMetrics': 'Usage Metrics',
  'providerSettings.validate': 'Validate',
  'providerSettings.validating': 'Validating...',
  'queueMonitor.activeTasks': 'ACTIVE TASKS',
  'queueMonitor.allowed': 'Allowed',
  'queueMonitor.approvalRequired': 'Approval Required',
  'queueMonitor.compactions': 'COMPACTIONS',
  'queueMonitor.completed': 'Completed',
  'queueMonitor.contextSessions': 'CONTEXT SESSIONS',
  'queueMonitor.contextStatusTitle': 'Context Compaction Status',
  'queueMonitor.contextTokens': 'CONTEXT TOKENS',
  'queueMonitor.denied': 'Denied',
  'queueMonitor.depth': 'depth',
  'queueMonitor.description': 'Background task pipeline and agent execution streams.',
  'queueMonitor.dismissReview': 'Dismiss',
  'queueMonitor.enqueued': 'Enqueued',
  'queueMonitor.eventAt': 'Event at',
  'queueMonitor.executionStream': 'Execution Stream',
  'queueMonitor.generated': 'Generated',
  'queueMonitor.hookExecutions': 'HOOK EXECUTIONS',
  'queueMonitor.hookFailures': 'HOOK FAILURES',
  'queueMonitor.hookNotifications': 'HOOK NOTIFICATIONS',
  'queueMonitor.hooksEnabled': 'HOOKS ENABLED',
  'queueMonitor.hottestSession': 'HOTTEST SESSION',
  'queueMonitor.lastDecision': 'Last decision',
  'queueMonitor.lastRun': 'Last run',
  'queueMonitor.loopBlocks': 'Loop Blocks',
  'queueMonitor.maxDepth': 'Max Depth',
  'queueMonitor.messages': 'Messages',
  'queueMonitor.model': 'model',
  'queueMonitor.modelGateway': 'MODEL GATEWAY',
  'queueMonitor.noActiveProvider': 'No active provider',
  'queueMonitor.noSubagentRuns': 'No subagent runs observed.',
  'queueMonitor.noToolPolicyDecisions': 'No tool policy decisions yet.',
  'queueMonitor.pathBlocks': 'Path Blocks',
  'queueMonitor.pendingTasks': 'PENDING TASKS',
  'queueMonitor.polling': 'Polling...',
  'queueMonitor.pollTasks': 'Poll Tasks',
  'queueMonitor.preparingContext': 'Preparing...',
  'queueMonitor.recentDecisions': 'Recent Decisions',
  'queueMonitor.reviewSummary': 'Review Summary',
  'queueMonitor.running': 'Running',
  'queueMonitor.sessionStart': 'session-start',
  'queueMonitor.sourceSession': 'Source Session',
  'queueMonitor.startingContext': 'Starting...',
  'queueMonitor.startNewNow': 'Start New Now',
  'queueMonitor.startNewWithContext': 'Start New with Context',
  'queueMonitor.startNewWithContextHelp':
    'Review generated summary before starting a new context session with carried state.',
  'queueMonitor.subagentOrchestration': 'Subagent Orchestration',
  'queueMonitor.summary': 'summary',
  'queueMonitor.targetSession': 'Target Session',
  'queueMonitor.tokens': 'Tokens',
  'queueMonitor.toolPolicyDecisions': 'Tool Policy Decisions',
  'queueMonitor.total': 'Total',
  'suites.deploy': 'Deploy Subagent',
  'suites.description': 'Manage active LLM agents and the delegation graph.',
  'suites.subs': 'Subs',
  'triage.analyze': 'Analyze',
  'triage.clear': 'Clear',
  'triage.description': 'Active Discrepancies and Escalations',
  'triage.enclavesActive': 'ENCLAVES Active',
  'triage.export': 'Export Log',
  'triage.filter': 'Filter',
  'triage.noRelatedMemory': 'No related memory found for this query.',
  'triage.received': 'RECEIVED',
  'triage.search': 'Search',
  'triage.searchPlaceholder': 'Search memory for triage context',
  'triage.source': 'SOURCE',
  'triage.status': 'STATUS',
  'triage.topic': 'TOPIC',
  'vault.asset': 'ASSET',
  'vault.clearAll': 'Clear All',
  'vault.description': 'Secure document storage and local-only environment encryption.',
  'vault.dragDrop': 'Drag and drop files to secure vault',
  'vault.empty': 'The vault is currently empty.',
  'vault.lockVault': 'Lock Vault',
  'vault.security': 'SECURITY',
  'vault.size': 'SIZE',
  'vault.type': 'TYPE',
  'vault.upload': 'Upload Document',
  'vault.uploading': 'Uploading...',
  'weeklyReview.compileReport': 'Compile Report',
  'weeklyReview.compiling': 'Compiling...',
  'weeklyReview.description': 'Aggregated executive briefing across all active domains.',
  'weeklyReview.enabledJobs': 'Enabled Jobs',
  'weeklyReview.failedJobs': 'Failed Jobs',
  'weeklyReview.lastTick': 'Last tick',
  'weeklyReview.noIncreasedRisks': 'No increased risks reported.',
  'weeklyReview.noMajorImprovements': 'No major improvements reported.',
  'weeklyReview.noSlips': 'No slips reported.',
  'weeklyReview.schedulerSummary': 'Scheduler Weekly Summary',
  'weeklyReview.successfulJobs': 'Successful Jobs',
  'weeklyReview.weekEnding': 'Week Ending',
  'weeklyReview.whatImproved': 'WHAT IMPROVED?',
  'weeklyReview.whatRiskIncreased': 'WHAT RISK INCREASED?',
  'weeklyReview.whatSlipped': 'WHAT SLIPPED?'
}
