export const enSettingsTranslations: Record<string, string> = {
  'settings.add': 'Add',
  'settings.appearance': 'Appearance',
  'settings.approve': 'Approve',
  'settings.channels.accessRules': 'Channel Access Rules',
  'settings.channels.allowAllAgentsTelegram': 'Allow all virtual employees to use Telegram routing',
  'settings.channels.approvedTelegramAgents': 'Approved Telegram Agent IDs',
  'settings.channels.approvedTelegramAgentsPlaceholder': 'mira, eva, julia',
  'settings.channels.description':
    'SQLite-backed channel policy used by onboarding and runtime routing.',
  'settings.channels.errorLoad': 'Failed to load channel configuration from SQLite.',
  'settings.channels.errorSave': 'Failed to save channel configuration.',
  'settings.channels.provider': 'Channel Provider',
  'settings.channels.providerCredentials': 'Provider Credentials (local SQLite only)',
  'settings.channels.save': 'Save Channel Configuration',
  'settings.channels.successSave': 'Channel configuration saved to SQLite runtime store.',
  'settings.channels.telegramChannelId': 'Telegram Channel ID',
  'settings.channels.title': 'Channel Runtime Configuration',
  'settings.channels.webhookSubscriptionUri': 'Webhook Subscription URI',
  'settings.cronExpression': 'Cron Expression',
  'settings.darkMode': 'Dark Mode',
  'settings.delete': 'Delete',
  'settings.description': 'Configure operational parameters and interface localization.',
  'settings.engineSelector': 'Engine Selector',
  'settings.language': 'Language',
  'settings.lastRun': 'Last run',
  'settings.lifecycle.affectedEmployees': 'Affected employees',
  'settings.lifecycle.commitDataInput': 'Commit Data Input Update',
  'settings.lifecycle.commitKpi': 'Commit KPI Update',
  'settings.lifecycle.commitProfile': 'Commit Profile Update',
  'settings.lifecycle.commitSkill': 'Commit Skill Update',
  'settings.lifecycle.createDataInput': 'Create Data Input and Refresh',
  'settings.lifecycle.createDataInputFailed': 'Failed to create data input.',
  'settings.lifecycle.createDataInputSuccess': 'Data input created and schema refreshed.',
  'settings.lifecycle.createDataInputTitle': 'Create New Data Input (Schema + Source)',
  'settings.lifecycle.currentBackstory': 'Current Backstory',
  'settings.lifecycle.currentContentPreview': 'Current Content Preview',
  'settings.lifecycle.currentGoal': 'Current Goal',
  'settings.lifecycle.currentSkillMarkdown': 'Current Skill Markdown',
  'settings.lifecycle.currentTarget': 'Current Target',
  'settings.lifecycle.currentUpload': 'Current Upload',
  'settings.lifecycle.currentValue': 'Current Value',
  'settings.lifecycle.dataInputSectionTitle': 'Data Input Upload and Diff',
  'settings.lifecycle.draftQueueEmpty': 'No pending lifecycle drafts.',
  'settings.lifecycle.draftQueueTitle': 'Pending Lifecycle Draft Queue',
  'settings.lifecycle.feedbackLoop':
    'Feedback loop: use contextual quick edits from operational screens, then finalize or audit in this control center.',
  'settings.lifecycle.kpiSectionTitle': 'KPI Draft and Diff',
  'settings.lifecycle.newDataInputDescription': 'New Data Input Description',
  'settings.lifecycle.newDataInputFileContent': 'Optional Uploaded File Content',
  'settings.lifecycle.newDataInputId': 'New Data Input ID (kebab-case)',
  'settings.lifecycle.newDataInputName': 'New Data Input Name',
  'settings.lifecycle.newDataInputRequiredFields': 'Required Fields (comma separated)',
  'settings.lifecycle.newDataInputSampleSource': 'Sample Source',
  'settings.lifecycle.newDataInputSchemaType': 'Schema Type',
  'settings.lifecycle.newDataInputUploadName': 'Optional Uploaded File Name',
  'settings.lifecycle.noUploadedSource': 'No uploaded source',
  'settings.lifecycle.profileSectionTitle': 'Profile Draft and Diff',
  'settings.lifecycle.proposedBackstory': 'Proposed Backstory',
  'settings.lifecycle.proposedContent': 'Proposed Content',
  'settings.lifecycle.proposedGoal': 'Proposed Goal',
  'settings.lifecycle.proposedSkillMarkdown': 'Proposed Skill Markdown',
  'settings.lifecycle.proposedTarget': 'Proposed Target',
  'settings.lifecycle.proposedUploadName': 'Proposed Upload Name',
  'settings.lifecycle.proposedValue': 'Proposed Value',
  'settings.lifecycle.readOnlyMode': 'Read-Only',
  'settings.lifecycle.registryExplorerTitle':
    'Registry Explorer (Keyword + Directory + File Editor)',
  'settings.lifecycle.registryFilePreview': 'File Preview',
  'settings.lifecycle.registryKeyword': 'Keyword Filter',
  'settings.lifecycle.registryNoFiles': 'No files matched the current filters.',
  'settings.lifecycle.registryNoSelection': 'Select a file to preview content.',
  'settings.lifecycle.registryRefresh': 'Refresh File Index',
  'settings.lifecycle.registrySaveFailed': 'Failed to save markdown.',
  'settings.lifecycle.registrySaveMarkdown': 'Save Markdown',
  'settings.lifecycle.registrySaveSuccess': 'Markdown saved to registry.',
  'settings.lifecycle.registrySectionFilter': 'Directory Filter (e.g. workflows/mira)',
  'settings.lifecycle.registryUploadFailed': 'Failed to upload file.',
  'settings.lifecycle.registryUploadFile': 'Upload Full File',
  'settings.lifecycle.registryUploadSuccess': 'File uploaded and registry refreshed.',
  'settings.lifecycle.registryUploadTarget': 'Upload Target Directory',
  'settings.lifecycle.reviewFailed': 'Draft review failed.',
  'settings.lifecycle.reviewSuccess': 'Draft review completed.',
  'settings.lifecycle.skillSectionTitle': 'Global Skill Draft and Diff',
  'settings.lifecycle.subtitle':
    'Centralized lifecycle control with side-by-side current vs improved drafts.',
  'settings.lifecycle.title': 'Registry Manager',
  'settings.lifecycle.uploadSeedFile': 'Upload Seed File',
  'settings.lifecycle.uploadUpdateDataFile': 'Upload/Update Data File',
  'settings.lifecycle.writeMode': 'Write Mode',
  'settings.localization': 'Localization',
  'settings.nextRun': 'Next run',
  'settings.openProviderSettings': 'Open Provider Settings',
  'settings.openRegistryViewer': 'Registry Viewer (Internal)',
  'settings.pause': 'Pause',
  'settings.preferredModelProvider': 'Preferred Model Provider',
  'settings.proposedAt': 'Proposed at',
  'settings.provider.gemini': 'Gemini',
  'settings.provider.lmstudio': 'LM Studio',
  'settings.provider.openrouter': 'OpenRouter',
  'settings.reducedMotion': 'Reduce UI motion',
  'settings.registry.loadedAt': 'Loaded:',
  'settings.registry.modules': 'Module Manifests',
  'settings.registry.reload': 'Reload Registry',
  'settings.registry.sections': 'Registry Inventory',
  'settings.registry.skills': 'Skill Documents',
  'settings.registry.subtitle': 'Live registry source-of-truth inspector with auto refresh.',
  'settings.registry.title': 'Registry Viewer',
  'settings.registry.version': 'Version:',
  'settings.reject': 'Reject',
  'settings.resume': 'Resume',
  'settings.review.modal.approveLabel': 'Approve',
  'settings.review.modal.approveNote': 'Approval Note (Optional)',
  'settings.review.modal.approveNotePlaceholder': 'Record optional feedback...',
  'settings.review.modal.confirmApprove': 'Confirm Approve',
  'settings.review.modal.confirmReject': 'Confirm Reject',
  'settings.review.modal.noteMinLength': 'Minimum 4 characters required',
  'settings.review.modal.noteRequired': 'Required: provide feedback for improvement',
  'settings.review.modal.rejectLabel': 'Reject',
  'settings.review.modal.rejectNote': 'Rejection Reason (Required)',
  'settings.review.modal.rejectNotePlaceholder':
    'Explain why this is rejected so the system can improve...',
  'settings.review.modal.selectAction': 'Choose an action below.',
  'settings.review.modal.title': 'Review Governance Action',
  'settings.runNow': 'Run Now',
  'settings.scheduleDescription': 'Manage recurring daily and weekly automations.',
  'settings.scheduleManagement': 'Schedule Management',
  'settings.scheduleName': 'Schedule Name',
  'settings.scheduleProposalQueue': 'Pending Schedule Proposals',
  'settings.scheduleProposalQueueEmpty': 'No pending schedule proposals.',
  'settings.status': 'Status',
  'settings.sync.description':
    'Configure automated sync cadence and cron pipelines between local SQLite and remote vault.',
  'settings.sync.enableCron': 'Enable sync cron jobs',
  'settings.sync.enablePullCron': 'Enable pull cron (Vault -> DB)',
  'settings.sync.enablePushCron': 'Enable push cron (DB -> Vault)',
  'settings.sync.health.autoRefreshEnabled': 'Enable Sync Health auto-refresh',
  'settings.sync.health.autoRefreshHint':
    'Minimum 5000 ms. Used by the settings screen Sync Health widget.',
  'settings.sync.health.autoRefreshIntervalMs': 'Sync Health auto-refresh interval (ms)',
  'settings.sync.health.empty': 'No sync health snapshot available yet.',
  'settings.sync.health.initialized': 'Initialized',
  'settings.sync.health.integrity': 'Integrity',
  'settings.sync.health.integrity.invalid': 'INVALID',
  'settings.sync.health.integrity.issues': 'Integrity Issues',
  'settings.sync.health.integrity.unknown': 'UNKNOWN',
  'settings.sync.health.integrity.valid': 'VALID',
  'settings.sync.health.lastRun': 'Last Run',
  'settings.sync.health.pull.title': 'Latest Pull',
  'settings.sync.health.pullNow': 'Pull Now',
  'settings.sync.health.push.title': 'Latest Push',
  'settings.sync.health.pushNow': 'Push Now',
  'settings.sync.health.queue.completed': 'Completed',
  'settings.sync.health.queue.pending': 'Pending/Failed',
  'settings.sync.health.queue.running': 'Running',
  'settings.sync.health.queue.title': 'Sync Queue',
  'settings.sync.health.refresh': 'Refresh',
  'settings.sync.health.timer': 'Push Timer',
  'settings.sync.health.title': 'Sync Health',
  'settings.sync.intervalHint':
    'Minimum 30000 ms. Controls push timer cadence in the main process.',
  'settings.sync.intervalMs': 'Background Push Interval (ms)',
  'settings.sync.pullCronExpression': 'Pull Cron Expression',
  'settings.sync.pushCronExpression': 'Push Cron Expression',
  'settings.sync.title': 'Sync Settings',
  'settings.systemPreferences': 'System Preferences',
  'settings.taskAuditLog': 'Task Audit Log',
  'settings.taskAuditLogEmpty': 'No task audit entries available.',
  'settings.theme.dark': 'Dark',
  'settings.theme.light': 'Light',
  'settings.theme.system': 'System',
  'settings.themeMode': 'Theme Mode'
}
